version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    ruby-app: 
        build: 
            context: ./chat-system
            dockerfile: Dockerfile
        command: >
            bash -c "
            ./bin/rails db:create && ./bin/rails db:migrate &&
            ./bin/rails server
            "
        volumes: 
            - ".:/chat-service"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            SECRET_KEY_BASE: secret_key_base
            CHAT_SYSTEM_DATABASE_PASSWORD: password