version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
        environment:
            discovery.type: single-node
            cluster.name: elasticsearch
            xpack.security.enabled: false
            http.cors.enabled: true
            http.cors.allow-origin: "*"
        ports:
            - "9200:9200"
            - "9300:9300"

    redis:
        image: redis
        restart: always
        ports:
            - "6378:6379"
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    ruby-app: 
        build: ./chat-system
        restart: always
        command: >
            bash -c "
            ./bin/rails db:create && ./bin/rails db:migrate &&
            ./bin/rails server
            "
        volumes: 
            - ".:/chat-service"
        ports: 
            - "3001:3000"
        depends_on:
            - db
            - redis
            - elasticsearch
        links:
            - db
            - redis
            - elasticsearch
        environment:
            SECRET_KEY_BASE: secret_key_base
            CHAT_SYSTEM_DATABASE_PASSWORD: password
            REDIS_URL: redis://redis:6379/0
            ELASTICSEARCH_URL: http://elasticsearch:9200
    sidekiq:
        build: ./chat-system
        command: bundle exec sidekiq /
                echo "Sidekiq is running"
        restart: always
        # volumes:
        # - .:/sidekiq
        depends_on:
        - db
        - redis
        - ruby-app
        - elasticsearch
        links:
        - db
        - redis
        - ruby-app
        - elasticsearch 
        environment:
            REDIS_URL: redis://redis:6379/0
            SECRET_KEY_BASE: secret_key_base
            ELASTICSEARCH_URL: http://elasticsearch:9200

    golang-app:
        build: ./creation-system-go
        restart: always
        volumes:
            - ".:/creation-service"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - elasticsearch
        links:
            - db
            - redis
            - elasticsearch
        environment:
            PORT: 8000
            SECRET_KEY_BASE: secret_key_base
            CHAT_SYSTEM_DATABASE_PASSWORD: password
            REDIS_URL: redis:6379
            ELASTICSEARCH_URL: http://elasticsearch:9200
