version: '2'
services:
    redis:
        image: redis
        restart: always
        ports:
            - "6378:6379"
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    ruby-app: 
        build: .
        command: >
            bash -c "
            ./bin/rails db:create && ./bin/rails db:migrate &&
            ./bin/rails server
            "
        volumes: 
            - ".:/chat-service"
        ports: 
            - "3001:3000"
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        environment:
            SECRET_KEY_BASE: secret_key_base
            CHAT_SYSTEM_DATABASE_PASSWORD: password
            REDIS_URL: redis://redis:6379/0
    sidekiq:
        build: .
        command: bundle exec sidekiq /
                echo "Sidekiq is running"
        # volumes:
        # - .:/sidekiq
        depends_on:
        - db
        - redis
        - ruby-app
        environment:
            REDIS_URL: redis://redis:6379/0
            SECRET_KEY_BASE: secret_key_base